### ISSUE TITLE
webpack could not find module 'socket.io-client'

### ISSUE THREAD

**Issue by shmuelios** [mean-expert-official/sdk-builder-starter#1]
Hi great project. I had a little trouble with. ng serve

it couldn't find the module.
This fixed it for me.

src/typings.d.ts
declare module 'socket.io-client' {
    var e: any;
    export = e;
}

Thanks

**Comment by jonathan-casarrubias** [comment]
Hi @shmuelios thanks for reaching out.

The current right approach to install types is natively provided by nativescript.

In the case that the PubSub is enabled, then the optimal is to install

``` sh
$ npm install @types/socket.io-client
```

and the install it in tsconfig.json

Anyway, Since I know the real time is getting so popular I just pushed the starter with all what I just described already installed.

Enjoy!!!
Jon

**Comment by shmuelios** [comment]
Jon thanks and fast! :+1: 

I'm still absorbing the node universe!

One thing I have found maybe not the place to ask. so no problem if you don't respond.
I'm having to switch my node 
"nvm use 4.5.0" for
"slc loopback: ..." commands. not a problem just wondered if I was doing it wrong.
"ng serve" I have to switch "nvm use 6.5.0" to latest version only since they moved to webpack I think.

I realise there are two maintained releases for a reason.

**Comment by jonathan-casarrubias** [comment]
@shmuelios I always use node 6.5.0 for both, is just that if you already installed your node_modules with another version you may need to wipe that folder and install with the preferred version.

If you decide to go 6.5.0 -recommended- then just remove the node_modules from your loopback project and you may also need to uninstall the strongloop global package and install it again.

This because the configuration is different depending the version of node, so you may want to run the project with different version than you originally installed and the npm configuration will differ. 

Hope it helps.

Cheers!
Jon

**Comment by shmuelios** [comment]
I thought I had an odd use case. that worked easily. 

Thanks again!
